/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './angular2-social-login.module';
import * as import2 from './auth.service';
import * as import3 from '@angular/core/src/di/injector';
class Angular2SocialLoginModuleInjector extends import0.NgModuleInjector<import1.Angular2SocialLoginModule> {
  _Angular2SocialLoginModule_0:import1.Angular2SocialLoginModule;
  __AuthService_1:import2.AuthService;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _AuthService_1():import2.AuthService {
    if ((this.__AuthService_1 == null)) { (this.__AuthService_1 = new import2.AuthService()); }
    return this.__AuthService_1;
  }
  createInternal():import1.Angular2SocialLoginModule {
    this._Angular2SocialLoginModule_0 = new import1.Angular2SocialLoginModule();
    return this._Angular2SocialLoginModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Angular2SocialLoginModule)) { return this._Angular2SocialLoginModule_0; }
    if ((token === import2.AuthService)) { return this._AuthService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Angular2SocialLoginModuleNgFactory:import0.NgModuleFactory<import1.Angular2SocialLoginModule> = new import0.NgModuleFactory(Angular2SocialLoginModuleInjector,import1.Angular2SocialLoginModule);